//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesxBoleta
    {
        public int Boleta_id_boleta { get; set; }
        public int Productos_id_producto { get; set; }
        public int cantidad_producto_boleta { get; set; }
        public double precio_unitario { get; set; }
        public int importe_producto_boleta { get; set; }
        public double monto_total { get; set; }
    
        public virtual Boleta Boleta { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
