//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.DetallesxBoleta = new HashSet<DetallesxBoleta>();
            this.DetallesxFactura = new HashSet<DetallesxFactura>();
        }
    
        public int id_producto { get; set; }
        public int codigo_producto { get; set; }
        public string nombre_producto { get; set; }
        public double precio { get; set; }
        public int Proveedores_id_proveedor { get; set; }
        public int Empleados_id_empleados { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesxBoleta> DetallesxBoleta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesxFactura> DetallesxFactura { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
